version: '3'
services:
  nginx:
    image: nginx:1.19.10
    ports: 
      - '8080:80'
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html/

  app:
    build: ./app
    volumes:
      - .:/var/www/html/
      - /var/www/html/laravel-react/node_modules
    depends_on:
      - mysql 

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: moticker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=password
    depends_on:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
volumes:
  mysql-data: